"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import ReviewFlow, {flowStep, type Case} from "./review-flow";

type Candidate={id:string;sourceId:string;canonicalUrl:string;lane:string;medium:string;era:string;status:string;caseCount:number;error:string|null;attemptedAt:number|null};
type AutomationRun={id:string;status:string;startedAt:number;captureStatus:string|null;researchStatus:string|null;error:string|null};
export default function Editor(){
 const [cases,setCases]=useState<Case[]>([]),[selected,setSelected]=useState<string|null>(null),[showIntake,setShowIntake]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loaded,setLoaded]=useState(false),[accessDenied,setAccessDenied]=useState(false);
 const [discovery,setDiscovery]=useState("Checking original source indexes…");
 const [candidates,setCandidates]=useState<Candidate[]>([]),[processing,setProcessing]=useState(false);
 const [automationRuns,setAutomationRuns]=useState<AutomationRun[]>([]);
 const [openedAt]=useState(()=>Date.now());
 const [monitoring,setMonitoring]=useState("Exception-only email alerts: two failed runs in a row, no capture in 72 h, spend above 75% of the monthly limit, key expiring within 21 days. Each at most once a day.");
 async function sendTestAlert(){setBusy(true);setError("");setNotice("");try{const res=await fetch("/api/editor/alerts",{method:"POST"});const out=await res.json() as {delivery?:{ok:boolean;error?:string;id?:string};checks?:Record<string,string>;wouldAlert?:string[]};if(!res.ok||!out.delivery?.ok)throw Error(out.delivery?.error||"Test alert could not be sent");setNotice(`Test alert sent to the configured address (Resend id ${out.delivery.id||"n/a"}). Live checks: ${Object.entries(out.checks||{}).map(([k,v])=>`${k}: ${v}`).join(" · ")}${out.wouldAlert?.length?` · would alert now: ${out.wouldAlert.join(", ")}`:""}`);setMonitoring(`Last test alert ${new Date().toLocaleString()}.`)}catch(e){setError(e instanceof Error?e.message:"Test alert failed")}finally{setBusy(false)}}
 const refreshIntake=useCallback(async()=>{const r=await fetch("/api/editor/intake",{cache:"no-store"});if(r.ok){const data=await r.json() as {candidates:Candidate[]};setCandidates(data.candidates||[])}},[]);
 const refresh=useCallback(async()=>{const res=await fetch("/api/editor/cases",{cache:"no-store"});const data=await res.json() as {cases?:Case[];error?:string};if(!res.ok){if(res.status===401||res.status===403)setAccessDenied(true);throw Error(data.error||"Could not load the checking queue.")}setAccessDenied(false);const rows=data.cases||[];setCases(rows);setSelected(current=>current&&rows.some(x=>x.id===current)?current:rows[0]?.id||null);setLoaded(true);const status=await fetch("/api/editor/automation-status",{cache:"no-store"});if(status.ok){const payload=await status.json() as {runs:AutomationRun[]};setAutomationRuns(payload.runs||[])}return rows},[]);
 useEffect(()=>{queueMicrotask(()=>{void refresh().then(async()=>{
   const res=await fetch("/api/editor/discover",{method:"POST"});
   const data=await res.json() as {results?:Array<{source:string;status:string;added:number;error?:string|null;reused?:boolean}>;historicAdded?:number;error?:string};
   if(!res.ok)throw Error(data.error||"Source discovery unavailable");
   const newCount=data.results?.filter(x=>x.status==="COMPLETE"&&!x.reused).reduce((total,x)=>total+(x.added||0),0)||0;
   setDiscovery(`${newCount} current source leads added · ${data.historicAdded||0} historical leads added · ${data.results?.filter(x=>x.status==="FAILED").length||0} source adapters need attention.`);
   await refreshIntake();
   await refresh();
 }).catch(e=>{setDiscovery(e instanceof Error?e.message:"Source discovery unavailable");setLoaded(true)})})},[refresh,refreshIntake]);
 async function researchCandidate(id:string,retry=false){setProcessing(true);setError("");try{const res=await fetch("/api/editor/intake",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,retry})});const result=await res.json() as {error?:string;caseIds?:string[];status?:string};await refreshIntake();await refresh();if(result.caseIds?.[0])setSelected(result.caseIds[0]);if(!res.ok)throw Error(result.error||"Research unavailable");setNotice(`Lead ${result.status?.toLowerCase()||"processed"}. ${result.caseIds?.length||0} private cases captured.`)}catch(e){setError(e instanceof Error?e.message:"Could not process lead")}finally{setProcessing(false)}}
 const current=cases.find(x=>x.id===selected);
 async function automate(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const sourceUrl=String(new FormData(form).get("sourceUrl")||"");setBusy(true);setError("");setNotice("Fetching the original and extracting exact claim candidates.");try{const res=await fetch("/api/editor/automate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceUrl})});const out=await res.json() as {error?:string;caseIds?:string[];message?:string};await refresh();if(out.caseIds?.[0])setSelected(out.caseIds[0]);if(!res.ok)throw Error(`${out.error||"Automated review stopped"}${out.caseIds?.length?` · ${out.caseIds.length} private case(s) preserved`:""}`);setNotice(`${out.caseIds?.length||0} claim candidate(s) captured. Compare the original and approve each before research.`);form.reset()}catch(err){setError(err instanceof Error?err.message:"Automated capture failed");setNotice("")}finally{setBusy(false)}}
 async function post(path:string,payload:Record<string,unknown>,message:string){setBusy(true);setError("");setNotice("");try{const res=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const out=await res.json() as {error?:string;details?:unknown;id?:string;caseIds?:string[];message?:string};if(!res.ok)throw Error(out.error||"This step could not be recorded.");setNotice(out.message||message);if(out.id&&path==="/api/editor/drafts"){setSelected(out.id);setShowIntake(false)}await refresh();if(out.caseIds?.[0])setSelected(out.caseIds[0]);return true}catch(e){setError(e instanceof Error?e.message:"Request failed");return false}finally{setBusy(false)}}
 function submit(path:string,message:string,transform?:(data:Record<string,string>)=>Record<string,unknown>){return(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;let payload:Record<string,unknown>=data;if(transform){try{payload=transform(data)}catch(err){setError(err instanceof Error?err.message:"Invalid input");return}}void post(path,payload,message).then(ok=>{if(ok)form.reset()})}}
 const base=current?"/api/editor/cases/"+encodeURIComponent(current.id):"";
 return <><header className="topbar"><Link className="brand" href="/">ON <span>RECORD</span><i/></Link><nav><Link href="/records">Published record</Link><small>PRIVATE CHECKING INSTRUMENT</small></nav></header>
 <main className="checking-shell"><div className="instrument-head"><div><div className="eyebrow">EDITORIAL WORKSPACE · METHODOLOGY CONTROLLED</div><h1>Cases to review</h1><p>The scheduler captures statements and drafts research on its own. Your part is four short steps per case: check the source, judge the claim, tick the evidence that holds, and finish. Nothing you do here is public until you publish.</p></div></div>
 <div className="discovery-status" role="status"><b>Source monitoring</b><span>{discovery}</span><small>Scans when this workspace opens. Captures and private research run on the schedule (13:00 and 19:00 UTC) or when you tap a lead below; both draw on the same daily budget.</small></div>
 {!accessDenied&&loaded&&<section className="discovery-status" aria-label="Scheduled intake"><b>Scheduled intake</b>{automationRuns.length?<><span>{new Date(automationRuns[0].startedAt).toLocaleString()} · {automationRuns[0].status} · capture {automationRuns[0].captureStatus||"pending"} · research {automationRuns[0].researchStatus||"pending"}</span>{automationRuns[0].error&&<small>{automationRuns[0].error}</small>}</>:<span>No scheduled run recorded yet.</span>}<div className="monitoring-line"><b>Monitoring</b> <span>{monitoring}</span> <Button type="button" disabled={busy} onClick={()=>void sendTestAlert()}>Send test alert</Button></div></section>}

 {accessDenied&&<div role="alert" className="form-error">Editor sign-in is required in this browser. <Link href="/login?return_to=%2Feditor">Sign in to On Record →</Link></div>}
 {error&&!accessDenied&&<div role="alert" className="form-error">{error}</div>}{notice&&<div role="status" className="form-success">{notice}</div>}
 <div className="instrument-layout"><aside className="case-queue"><div className="eyebrow">CASES IN REVIEW</div>{!loaded&&<p>Loading cases…</p>}{loaded&&!cases.length&&!accessDenied&&<div className="empty">No source has entered the checking instrument yet. Capture one to begin.</div>}{cases.map(x=><button type="button" key={x.id} className={"case-item "+(selected===x.id?"active":"")} onClick={()=>setSelected(x.id)}><span>{x.issue||"Unclassified"} · {({source:"check source",judge:"judge",evidence:"evidence",finish:"finish",done:"published",closed:"closed"})[flowStep(x)]}</span><b>{x.speakerName}</b><small>{x.exactText}</small></button>)}</aside>
 <div className="instrument-main">{current?<><div className="case-summary"><div className="eyebrow">CASE {current.id} · {current.stage.replaceAll("_"," ")}</div><h2>{current.speakerName}</h2><p className="case-quote">“{current.exactText}”</p><div className="canonical-box"><strong>Normalized proposition</strong><p>{current.canonicalProposition}</p></div><details><summary>Original captured communication</summary><pre>{current.originalContent}</pre><a href={current.canonicalUrl} target="_blank" rel="noopener noreferrer">Open original source ↗</a></details><Button type="button" disabled={busy||accessDenied} onClick={()=>void post(base+"/reextract",{},"Additional candidates ready for source review.")}>{busy?"Extracting…":"Find stronger claims in this source"}</Button></div>
<ReviewFlow current={current} busy={busy||accessDenied} post={post}/>
 </>:<div className="empty">{accessDenied?"Sign in as an authorized editor to use the checking instrument.":loaded?"Capture a source to start a checking case.":"Loading checking instrument…"}</div>}</div></div>
 <section className="intake-panel more-sources"><div className="eyebrow">MORE SOURCES</div><form className="auto-intake" onSubmit={automate}><label>Original public HTTPS communication<Input type="url" name="sourceUrl" placeholder="https://official-source.example/statement" required disabled={busy||accessDenied}/></label><Button type="submit" disabled={busy||accessDenied}>{busy?"Capturing…":"Extract claim candidates"}</Button><span>Compare the original and approve a claim before launching evidence research.</span></form><button type="button" className="manual-toggle" disabled={accessDenied} onClick={()=>setShowIntake(x=>!x)}>{showIntake?"Close manual capture":"Manual capture for inaccessible sources"}</button></section>
 {showIntake&&<form className="intake-panel" onSubmit={submit("/api/editor/drafts","Source captured as a candidate. It has no finding.",data=>{const at=new Date(data.publishedAt);if(Number.isNaN(at.getTime()))throw Error("Enter a valid publication time.");return {...data,publishedAt:at.toISOString()}})}><div><div className="eyebrow">STAGE 01</div><h2>Preserve the communication</h2><p>Paste the complete source text, then identify the exact factual sentence within it. Entering a URL does not authenticate the source.</p></div><div className="intake-grid"><label>Speaker or organization<Input name="speakerName" required minLength={2}/></label><label>Source type<select name="sourceType" defaultValue="social"><option value="social">Social post</option><option value="speech">Speech</option><option value="interview">Interview</option><option value="advertisement">Advertisement</option><option value="written">Written statement</option></select></label><label>Original source URL<Input name="canonicalUrl" type="url" required placeholder="https://…"/></label><label>Published at<Input name="publishedAt" type="datetime-local" required/></label><label className="wide">Complete original text or transcript<Textarea name="originalContent" required rows={5}/></label><label className="wide">Exact factual representation (verbatim substring)<Textarea name="exactText" required rows={2}/></label><label className="wide">Normalized factual proposition<Textarea name="canonicalProposition" required rows={2}/></label><label>Issue<Input name="issue" required/></label></div><Button type="submit" disabled={busy}>Save candidate source</Button></form>}
 <details className="source-desk"><summary>Source queue · {candidates.filter(x=>x.status==="QUEUED").length} queued · {candidates.filter(x=>x.status==="CAPTURED").length} captured · {candidates.filter(x=>x.status==="FAILED").length} failed</summary><section className="intake-panel"><div className="eyebrow">PRIVATE SOURCE DESK · FIRST 100 LEADS</div><h2>Source queue</h2><p>{candidates.filter(x=>x.status==="QUEUED").length} queued · {candidates.filter(x=>x.status==="CAPTURED").length} captured · {candidates.filter(x=>x.status==="FAILED").length} failed. Current reporting is prioritized; archived speeches and debates remain available for historical review.</p><div className="evidence-list">{candidates.slice(0,30).map(x=><article key={x.id}><span>{x.lane} · {x.era} · {x.medium} · {x.status}</span><b>{x.sourceId}</b><a href={x.canonicalUrl} target="_blank" rel="noopener noreferrer">Original source ↗</a>{x.error&&<small>{x.error}</small>}{(x.status==="QUEUED"||x.status==="FAILED"||(x.status==="PROCESSING"&&!!x.attemptedAt&&openedAt-x.attemptedAt>900000))&&x.lane!=="Multi-speaker"&&!x.medium.includes("needs-transcript")&&<Button type="button" disabled={processing} onClick={()=>void researchCandidate(x.id,x.status!=="QUEUED")}>{processing?"Capturing…":x.status!=="QUEUED"?"Recover captured source":"Capture this source"}</Button>}{(x.lane==="Multi-speaker"||x.medium.includes("needs-transcript"))&&<small>Check speaker turns or transcribe the original recording before extraction.</small>}</article>)}{!candidates.length&&<p>No leads recorded. Source scans start when this workspace opens.</p>}</div></section></details>
</main></>
}
